@startuml
skinparam backgroundcolor transparent

participant "Translator" as t
participant "Secret\nStorage" as sec
participant "Proxy" as p
participant "Public\nKey\nInfrastructure" as k

alt key exists
    t -> sec : Fetch Private Key
    activate sec
    return Return Private Key
else key does not exist
    t -> t : Generate Private Key
    t -> sec : Store Private Key
end

t -> k : Certificate Signing Request
activate k
    k -> k : Sign Certificate
return Signed Certificate

@enduml
