@startuml
skinparam backgroundcolor transparent

actor User as u
participant Frontend as fe
participant "Modern API" as m
participant "Legacy API" as l

u -> fe : Open web application
activate fe
return Authorize via IAM

u -> fe : Click "Call API" button
activate fe
    fe -> m : Call "/customers"
    activate m
    return Returns customer data
    
    fe -> m : Call "/orders"
    activate m

    alt USE_WIREPACT = true
        m -> l : Call "/orders"\nwith OIDC token
        activate l
        return Return order data
    else USE_WIREPACT = false
        m -> m : Transform credentials
        m -> l : Call "/orders"\nwith basic auth
        activate l
        return Return order data
    end

    return Return order data
return Present customer\nand order data

@enduml
