@startuml
skinparam backgroundcolor transparent

participant "Proxy" as p
participant "Translator" as t
participant "Destination" as d

[-> p : Incomming Communication
activate p
    p -> t : Forward HTTP Headers
    activate t
        t -> t : Extract Access Token
        t -> t : Validate Access Token on ZITADEL
    return HTTP 403 Forbidden
return HTTP 403 Forbidden

@enduml
