@startuml
skinparam backgroundcolor transparent

actor User as u
component [Identity and Access Management] as i

node "Cloud Environment" {
    component [Single Page Application] as c
    component [Cloud Native Application] as sa
    component [Legacy System] as sb

    c -> sa : OIDC
    sa -> sb : Basic\nAuthentication
}

u --> c : Accesses the App
c <--> i : Check Credentials / Tokens
i <--> sa

@enduml
