@startuml
skinparam backgroundcolor transparent
!define KubernetesPuml https://raw.githubusercontent.com/dcasati/kubernetes-PlantUML/master/dist

!include KubernetesPuml/kubernetes_Common.puml
!include KubernetesPuml/kubernetes_Context.puml
!include KubernetesPuml/kubernetes_Container.puml
!include KubernetesPuml/kubernetes_Simplified.puml

!include KubernetesPuml/OSS/KubernetesApi.puml
!include KubernetesPuml/OSS/KubernetesSvc.puml
!include KubernetesPuml/OSS/KubernetesPod.puml
!include KubernetesPuml/OSS/KubernetesDeploy.puml

Container(op, "Operator", "Operator")

Cluster_Boundary(dep, "Deployment") {
    Cluster_Boundary(po_2, "Pod") {
        Container(po2_c1, "Container", "Application")
        Container(po2_c2, "Container", "Sidecar 1")
        Container(po2_c3, "Container", "Sidecar 2")
    }
}

Container(gate, "API Gateway", "e.g. Ambassador")

KubernetesSvc(svc, "Service", "")

op --> dep : Manages Resources
op -> svc : Manages Resources

svc --> po2_c1 : Allows communication

gate -left-> svc : Routes communication

@enduml
