@startuml
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/materia-outline/puml-theme-materia-outline.puml

actor User as u
component [Zitadel IAM] as i

node "Cloud Environment" {
    component [Client\n(OIDC Capable)] as c
    component [Modern Backend\n(OIDC Capable)] as sa
    component [Legacy Backend\n(Basic Auth Capable)] as sb

    c -> sa : OIDC
    sa -> sb : Basic
}

u --> c
c <--> i
i <--> sa

@enduml
