@startuml

actor User as u
component [Zitadel IAM] as i

node "Cloud Environment" {
    component [Client\n(OIDC Capable)] as c
    component [Modern Backend\n(OIDC Capable)] as sa
    component [Legacy Backend\n(Basic Auth Capable)] as sb

    c -> sa : Call with\nOIDC Token
    sa -> sb : Call with\nBasic Auth Credentials
}

u --> c : Uses with OIDC
c <--> i : Checks Credentials
i <--> sa : Checks Credentials

@enduml
