@startuml

node "Application Pod" {
    component [Main Container] as m
    component [Sidecar A\n(Log Collector)] as sa
    component [Sidecar B\n(Monitoring Agent)] as sb
    database "File System" as f

    m -down- f
    sa -down- f
    sb -down- f
}

@enduml
