@startuml
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/materia-outline/puml-theme-materia-outline.puml

node "Cloud Environment" {
    component [Operator] as op
    component [Key Manager] as km

    package "Deployment A" as da {
        component [Software] as sw_a
        component [Envoy Proxy] as envoy_a
        component [Credential\nTranslator] as t_a
    }

    package "Deployment B" as db {
        component [Software] as sw_b
        component [Envoy Proxy] as envoy_b
        component [Credential\nTranslator] as t_b
    }
    
    op -[dashed]--> da : manages
    op -[dashed]--> db : manages

    km -[dashed]--> t_a : provides keys
    km -[dashed]--> t_b : provides keys

    envoy_a <---> envoy_b : communicate
    envoy_a <--> t_a : map credentials
    envoy_b <--> t_b : map credentials
    envoy_a <-> sw_a : relay
    envoy_b <--> sw_b : relay
}

@enduml
